"""Cultural programming presets for historical TV blocks."""

from typing import Dict


CULTURAL_PRESETS: Dict[str, Dict] = {
    "saturday_morning_cartoons": {
        "name": "Saturday Morning Cartoons",
        "description": "Classic weekend cartoon blocks from the golden age",
        "day": "saturday",
        "time_start": "08:00",
        "time_end": "12:00",
        "networks": ["NBC", "CBS", "ABC", "FOX"],
        "year_range": [1966, 2000],
        "recommended_year": 1985,
    },
    "tgif": {
        "name": "TGIF (Thank God It's Friday)",
        "description": "ABC's legendary Friday night comedy block",
        "day": "friday",
        "time_start": "20:00",
        "time_end": "22:00",
        "networks": ["ABC"],
        "year_range": [1989, 2000],
        "recommended_year": 1991,
    },
    "must_see_tv": {
        "name": "Must See TV",
        "description": "NBC's Thursday night comedy lineup",
        "day": "thursday",
        "time_start": "20:00",
        "time_end": "22:00",
        "networks": ["NBC"],
        "year_range": [1984, 2006],
        "recommended_year": 1995,
    },
    "sunday_night_disney": {
        "name": "The Wonderful World of Disney",
        "description": "Disney's Sunday night family programming",
        "day": "sunday",
        "time_start": "19:00",
        "time_end": "21:00",
        "networks": ["NBC", "ABC", "CBS"],
        "year_range": [1954, 2005],
        "recommended_year": 1985,
    },
    "after_school_specials": {
        "name": "After School Specials",
        "description": "Weekday afternoon educational programming",
        "day": "wednesday",
        "time_start": "16:00",
        "time_end": "17:00",
        "networks": ["ABC", "CBS", "NBC"],
        "year_range": [1972, 1997],
        "recommended_year": 1985,
    },
    "soap_operas": {
        "name": "Daytime Soap Operas",
        "description": "Classic daytime drama block",
        "day": "monday",
        "time_start": "12:00",
        "time_end": "16:00",
        "networks": ["ABC", "CBS", "NBC"],
        "year_range": [1960, 2010],
        "recommended_year": 1985,
    },
    "primetime_soaps": {
        "name": "Primetime Soaps",
        "description": "Evening drama serials like Dallas and Dynasty",
        "day": "friday",
        "time_start": "21:00",
        "time_end": "23:00",
        "networks": ["CBS", "ABC"],
        "year_range": [1978, 1991],
        "recommended_year": 1985,
    },
    "fox_sunday": {
        "name": "FOX Sunday Night",
        "description": "The Simpsons and animated comedy block",
        "day": "sunday",
        "time_start": "20:00",
        "time_end": "22:00",
        "networks": ["FOX"],
        "year_range": [1989, 2010],
        "recommended_year": 1995,
    },
    "snick": {
        "name": "SNICK (Saturday Night Nickelodeon)",
        "description": "Nickelodeon's Saturday night kids block",
        "day": "saturday",
        "time_start": "20:00",
        "time_end": "22:00",
        "networks": ["NICK"],
        "year_range": [1992, 2004],
        "recommended_year": 1995,
    },
    "late_night": {
        "name": "Late Night Talk Shows",
        "description": "Classic late night entertainment",
        "day": "monday",
        "time_start": "23:30",
        "time_end": "01:30",
        "networks": ["NBC", "CBS", "ABC"],
        "year_range": [1954, 2010],
        "recommended_year": 1992,
    },
    "saturday_night_live": {
        "name": "Saturday Night Live",
        "description": "NBC's legendary sketch comedy show",
        "day": "saturday",
        "time_start": "23:30",
        "time_end": "01:00",
        "networks": ["NBC"],
        "year_range": [1975, 2010],
        "recommended_year": 1990,
    },
    "monday_night_football": {
        "name": "Monday Night Football",
        "description": "ABC's primetime football tradition",
        "day": "monday",
        "time_start": "21:00",
        "time_end": "00:00",
        "networks": ["ABC"],
        "year_range": [1970, 2005],
        "recommended_year": 1985,
    },
}
