"""Classic shows database with metadata for historical TV lineups."""

from typing import Dict


CLASSIC_SHOWS_DATABASE: Dict[str, Dict] = {
    # --- NBC ---
    # 1950s-1960s
    "Bonanza": {"years": "1959-1973", "network": "NBC", "genre": "Western", "runtime": 60, "day_slots": ["sunday"]},
    "Dragnet": {"years": "1951-1959", "network": "NBC", "genre": "Drama", "runtime": 30, "day_slots": ["thursday"]},
    "I Dream of Jeannie": {"years": "1965-1970", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["monday", "tuesday"]},
    "Get Smart": {"years": "1965-1970", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["saturday"]},
    "Star Trek": {"years": "1966-1969", "network": "NBC", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["thursday", "friday"]},
    "The Man from U.N.C.L.E.": {"years": "1964-1968", "network": "NBC", "genre": "Action", "runtime": 60, "day_slots": ["monday", "tuesday"]},
    "The Virginian": {"years": "1962-1971", "network": "NBC", "genre": "Western", "runtime": 90, "day_slots": ["wednesday"]},
    "Wagon Train": {"years": "1957-1962", "network": "NBC", "genre": "Western", "runtime": 60, "day_slots": ["wednesday"]},
    "Rowan & Martin's Laugh-In": {"years": "1968-1973", "network": "NBC", "genre": "Variety", "runtime": 60, "day_slots": ["monday"]},
    "The Dean Martin Show": {"years": "1965-1974", "network": "NBC", "genre": "Variety", "runtime": 60, "day_slots": ["thursday"]},
    "Daniel Boone": {"years": "1964-1970", "network": "NBC", "genre": "Western", "runtime": 60, "day_slots": ["thursday"]},
    "The Flip Wilson Show": {"years": "1970-1974", "network": "NBC", "genre": "Variety", "runtime": 60, "day_slots": ["thursday"]},
    "Adam-12": {"years": "1968-1975", "network": "NBC", "genre": "Drama", "runtime": 30, "day_slots": ["saturday"]},
    "Ironside": {"years": "1967-1975", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "My World and Welcome to It": {"years": "1969-1970", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    # 1970s
    "Sanford and Son": {"years": "1972-1977", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "Chico and the Man": {"years": "1974-1978", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "Little House on the Prairie": {"years": "1974-1983", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["monday", "wednesday"]},
    "The Rockford Files": {"years": "1974-1980", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["friday"]},
    "Columbo": {"years": "1971-2003", "network": "NBC", "genre": "Mystery", "runtime": 90, "day_slots": ["sunday"]},
    "Emergency!": {"years": "1972-1979", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["saturday"]},
    "CHiPs": {"years": "1977-1983", "network": "NBC", "genre": "Action", "runtime": 60, "day_slots": ["saturday"]},
    "Diff'rent Strokes": {"years": "1978-1985", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday", "saturday"]},
    "The Facts of Life": {"years": "1979-1988", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["saturday"]},
    "Quincy, M.E.": {"years": "1976-1983", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["friday"]},
    "BJ and the Bear": {"years": "1979-1981", "network": "NBC", "genre": "Action", "runtime": 60, "day_slots": ["saturday", "tuesday"]},
    # 1980s-2000s
    "The Cosby Show": {"years": "1984-1992", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Cheers": {"years": "1982-1993", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Seinfeld": {"years": "1989-1998", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Friends": {"years": "1994-2004", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "ER": {"years": "1994-2009", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "Hill Street Blues": {"years": "1981-1987", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["thursday", "tuesday"]},
    "Miami Vice": {"years": "1984-1990", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["friday"]},
    "Family Ties": {"years": "1982-1989", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Night Court": {"years": "1984-1992", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday", "wednesday"]},
    "A Different World": {"years": "1987-1993", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Wings": {"years": "1990-1997", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday", "tuesday"]},
    "L.A. Law": {"years": "1986-1994", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "Frasier": {"years": "1993-2004", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday", "tuesday"]},
    "Will & Grace": {"years": "1998-2006", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Mad About You": {"years": "1992-1999", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday", "sunday"]},
    "The Fresh Prince of Bel-Air": {"years": "1990-1996", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Quantum Leap": {"years": "1989-1993", "network": "NBC", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["wednesday"]},
    "Law & Order": {"years": "1990-2010", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday", "monday"]},
    "The A-Team": {"years": "1983-1987", "network": "NBC", "genre": "Action", "runtime": 60, "day_slots": ["tuesday"]},
    "Knight Rider": {"years": "1982-1986", "network": "NBC", "genre": "Action", "runtime": 60, "day_slots": ["friday"]},
    "Hunter": {"years": "1984-1991", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["saturday"]},
    "St. Elsewhere": {"years": "1982-1988", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    "3rd Rock from the Sun": {"years": "1996-2001", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday", "sunday"]},
    "Just Shoot Me!": {"years": "1997-2003", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday", "thursday"]},
    "NewsRadio": {"years": "1995-1999", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "Homicide: Life on the Street": {"years": "1993-1999", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["friday"]},
    "The West Wing": {"years": "1999-2006", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    "Caroline in the City": {"years": "1995-1999", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Unsolved Mysteries": {"years": "1987-1999", "network": "NBC", "genre": "Mystery", "runtime": 60, "day_slots": ["wednesday", "friday"]},
    # 2010s-2020s
    "The Good Place": {"years": "2016-2020", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Brooklyn Nine-Nine": {"years": "2018-2021", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Parks and Recreation": {"years": "2009-2015", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday", "tuesday"]},
    "The Office": {"years": "2005-2013", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday", "tuesday"]},
    "30 Rock": {"years": "2006-2013", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Community": {"years": "2009-2014", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "This Is Us": {"years": "2016-2022", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "Superstore": {"years": "2015-2021", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Chicago Fire": {"years": "2012-present", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "Chicago P.D.": {"years": "2014-present", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    "Law & Order: SVU": {"years": "1999-present", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "Parenthood": {"years": "2010-2015", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["thursday", "tuesday"]},
    "Scrubs": {"years": "2001-2010", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday", "tuesday"]},
    "My Name Is Earl": {"years": "2005-2009", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday", "thursday"]},
    "Joey": {"years": "2004-2006", "network": "NBC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Medium": {"years": "2005-2011", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "Las Vegas": {"years": "2003-2008", "network": "NBC", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "The Apprentice": {"years": "2004-2017", "network": "NBC", "genre": "Reality", "runtime": 60, "day_slots": ["thursday"]},
    # --- CBS ---
    # 1950s-1960s
    "I Love Lucy": {"years": "1951-1957", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "The Honeymooners": {"years": "1955-1956", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["saturday"]},
    "The Twilight Zone": {"years": "1959-1964", "network": "CBS", "genre": "Sci-Fi", "runtime": 30, "day_slots": ["friday"]},
    "The Andy Griffith Show": {"years": "1960-1968", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "The Beverly Hillbillies": {"years": "1962-1971", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "Green Acres": {"years": "1965-1971", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "Petticoat Junction": {"years": "1963-1970", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "Hogan's Heroes": {"years": "1965-1971", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "Gilligan's Island": {"years": "1964-1967", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["saturday", "monday"]},
    "The Ed Sullivan Show": {"years": "1948-1971", "network": "CBS", "genre": "Variety", "runtime": 60, "day_slots": ["sunday"]},
    "Perry Mason": {"years": "1957-1966", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["saturday"]},
    "The Dick Van Dyke Show": {"years": "1961-1966", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "The Red Skelton Show": {"years": "1951-1971", "network": "CBS", "genre": "Variety", "runtime": 60, "day_slots": ["tuesday"]},
    "Lassie": {"years": "1954-1973", "network": "CBS", "genre": "Drama", "runtime": 30, "day_slots": ["sunday"]},
    "The Lucy Show": {"years": "1962-1968", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Rawhide": {"years": "1959-1965", "network": "CBS", "genre": "Western", "runtime": 60, "day_slots": ["friday"]},
    "Have Gun – Will Travel": {"years": "1957-1963", "network": "CBS", "genre": "Western", "runtime": 30, "day_slots": ["saturday"]},
    "My Three Sons": {"years": "1965-1972", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday", "saturday"]},
    "The Smothers Brothers Comedy Hour": {"years": "1967-1969", "network": "CBS", "genre": "Variety", "runtime": 60, "day_slots": ["sunday"]},
    # 1970s
    "Good Times": {"years": "1974-1979", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday", "wednesday"]},
    "The Waltons": {"years": "1972-1981", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "Maude": {"years": "1972-1978", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "Rhoda": {"years": "1974-1978", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "One Day at a Time": {"years": "1975-1984", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday", "monday"]},
    "WKRP in Cincinnati": {"years": "1978-1982", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "The Incredible Hulk": {"years": "1977-1982", "network": "CBS", "genre": "Action", "runtime": 60, "day_slots": ["friday"]},
    "Barnaby Jones": {"years": "1973-1980", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["friday"]},
    "Cannon": {"years": "1971-1976", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    "The White Shadow": {"years": "1978-1981", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    # 1980s-2000s
    "Murphy Brown": {"years": "1988-1998", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Dallas": {"years": "1978-1991", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["friday"]},
    "M*A*S*H": {"years": "1972-1983", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday", "tuesday"]},
    "Magnum, P.I.": {"years": "1980-1988", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "Simon & Simon": {"years": "1981-1989", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["thursday", "tuesday"]},
    "Murder, She Wrote": {"years": "1984-1996", "network": "CBS", "genre": "Mystery", "runtime": 60, "day_slots": ["sunday"]},
    "60 Minutes": {"years": "1968-present", "network": "CBS", "genre": "News", "runtime": 60, "day_slots": ["sunday"]},
    "Designing Women": {"years": "1986-1993", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Kate & Allie": {"years": "1984-1989", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Newhart": {"years": "1982-1990", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Knots Landing": {"years": "1979-1993", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "Cagney & Lacey": {"years": "1982-1988", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "The Dukes of Hazzard": {"years": "1979-1985", "network": "CBS", "genre": "Action", "runtime": 60, "day_slots": ["friday"]},
    "Falcon Crest": {"years": "1981-1990", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["friday"]},
    "Diagnosis: Murder": {"years": "1993-2001", "network": "CBS", "genre": "Mystery", "runtime": 60, "day_slots": ["thursday", "friday"]},
    "Touched by an Angel": {"years": "1994-2003", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["saturday", "sunday"]},
    "Walker, Texas Ranger": {"years": "1993-2001", "network": "CBS", "genre": "Action", "runtime": 60, "day_slots": ["saturday"]},
    "Everybody Loves Raymond": {"years": "1996-2005", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "The Nanny": {"years": "1993-1999", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "JAG": {"years": "1997-2005", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "CSI: Crime Scene Investigation": {"years": "2000-2015", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "The King of Queens": {"years": "1998-2007", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Survivor": {"years": "2000-present", "network": "CBS", "genre": "Reality", "runtime": 60, "day_slots": ["thursday"]},
    "Alice": {"years": "1976-1985", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday", "monday"]},
    "The Jeffersons": {"years": "1975-1985", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "All in the Family": {"years": "1971-1979", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["saturday", "monday"]},
    "The Mary Tyler Moore Show": {"years": "1970-1977", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["saturday"]},
    "The Bob Newhart Show": {"years": "1972-1978", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["saturday"]},
    "The Carol Burnett Show": {"years": "1967-1978", "network": "CBS", "genre": "Variety", "runtime": 60, "day_slots": ["saturday"]},
    "Hawaii Five-O": {"years": "1968-1980", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "Gunsmoke": {"years": "1955-1975", "network": "CBS", "genre": "Western", "runtime": 60, "day_slots": ["monday"]},
    # 2010s-2020s
    "The Big Bang Theory": {"years": "2007-2019", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday", "thursday"]},
    "NCIS": {"years": "2003-present", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "How I Met Your Mother": {"years": "2005-2014", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Two and a Half Men": {"years": "2003-2015", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "The Good Wife": {"years": "2009-2016", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Blue Bloods": {"years": "2010-present", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["friday"]},
    "Criminal Minds": {"years": "2005-2020", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    "Mom": {"years": "2013-2021", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Young Sheldon": {"years": "2017-2024", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "SEAL Team": {"years": "2017-2021", "network": "CBS", "genre": "Action", "runtime": 60, "day_slots": ["wednesday"]},
    "Becker": {"years": "1998-2004", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "CSI: Miami": {"years": "2002-2012", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "CSI: NY": {"years": "2004-2013", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday", "friday"]},
    "Without a Trace": {"years": "2002-2009", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "Cold Case": {"years": "2003-2010", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Chicago Hope": {"years": "1994-2000", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["monday", "thursday"]},
    "Nash Bridges": {"years": "1996-2001", "network": "CBS", "genre": "Drama", "runtime": 60, "day_slots": ["friday"]},
    "Cybill": {"years": "1995-1998", "network": "CBS", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    # --- ABC ---
    # 1950s-1960s
    "The Flintstones": {"years": "1960-1966", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "Bewitched": {"years": "1964-1972", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "The Addams Family": {"years": "1964-1966", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "Batman": {"years": "1966-1968", "network": "ABC", "genre": "Action", "runtime": 30, "day_slots": ["wednesday", "thursday"]},
    "The Fugitive": {"years": "1963-1967", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "Leave It to Beaver": {"years": "1958-1963", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday", "saturday"]},
    "The Donna Reed Show": {"years": "1958-1966", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "The Patty Duke Show": {"years": "1963-1966", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "The Outer Limits": {"years": "1963-1965", "network": "ABC", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["monday"]},
    "Combat!": {"years": "1962-1967", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "77 Sunset Strip": {"years": "1958-1964", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["friday"]},
    "Maverick": {"years": "1957-1962", "network": "ABC", "genre": "Western", "runtime": 60, "day_slots": ["sunday"]},
    "The Rifleman": {"years": "1958-1963", "network": "ABC", "genre": "Western", "runtime": 30, "day_slots": ["tuesday"]},
    "The Adventures of Ozzie and Harriet": {"years": "1952-1966", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "Ben Casey": {"years": "1961-1966", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    # 1970s
    "Welcome Back, Kotter": {"years": "1975-1979", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday", "tuesday"]},
    "Barney Miller": {"years": "1975-1982", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "The Six Million Dollar Man": {"years": "1974-1978", "network": "ABC", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday"]},
    "The Bionic Woman": {"years": "1976-1978", "network": "ABC", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["wednesday"]},
    "Starsky & Hutch": {"years": "1975-1979", "network": "ABC", "genre": "Action", "runtime": 60, "day_slots": ["wednesday", "saturday"]},
    "Eight Is Enough": {"years": "1977-1981", "network": "ABC", "genre": "Comedy", "runtime": 60, "day_slots": ["wednesday"]},
    "Taxi": {"years": "1978-1982", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "Soap": {"years": "1977-1981", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "The Brady Bunch": {"years": "1969-1974", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "The Partridge Family": {"years": "1970-1974", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "Kung Fu": {"years": "1972-1975", "network": "ABC", "genre": "Action", "runtime": 60, "day_slots": ["thursday"]},
    "The Mod Squad": {"years": "1968-1973", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "Marcus Welby, M.D.": {"years": "1969-1976", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    # 1980s-2000s
    "Dynasty": {"years": "1981-1989", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    "Full House": {"years": "1987-1995", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "Family Matters": {"years": "1989-1998", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "Growing Pains": {"years": "1985-1992", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday", "wednesday"]},
    "Who's the Boss?": {"years": "1984-1992", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "Roseanne": {"years": "1988-1997", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "Home Improvement": {"years": "1991-1999", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday", "wednesday"]},
    "NYPD Blue": {"years": "1993-2005", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "The Wonder Years": {"years": "1988-1993", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday", "wednesday"]},
    "Perfect Strangers": {"years": "1986-1993", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "Boy Meets World": {"years": "1993-2000", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "Step by Step": {"years": "1991-1998", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "Hangin' with Mr. Cooper": {"years": "1992-1997", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "The Drew Carey Show": {"years": "1995-2004", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "Spin City": {"years": "1996-2002", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "The Practice": {"years": "1997-2004", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Alias": {"years": "2001-2006", "network": "ABC", "genre": "Action", "runtime": 60, "day_slots": ["sunday"]},
    "Happy Days": {"years": "1974-1984", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "Laverne & Shirley": {"years": "1976-1983", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "Mork & Mindy": {"years": "1978-1982", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday", "sunday"]},
    "Three's Company": {"years": "1977-1984", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "The Love Boat": {"years": "1977-1986", "network": "ABC", "genre": "Comedy", "runtime": 60, "day_slots": ["saturday"]},
    "Fantasy Island": {"years": "1977-1984", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["saturday"]},
    "Charlie's Angels": {"years": "1976-1981", "network": "ABC", "genre": "Action", "runtime": 60, "day_slots": ["wednesday"]},
    "Moonlighting": {"years": "1985-1989", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "MacGyver": {"years": "1985-1992", "network": "ABC", "genre": "Action", "runtime": 60, "day_slots": ["monday"]},
    "Sabrina, the Teenage Witch": {"years": "1996-2003", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "Dharma & Greg": {"years": "1997-2002", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "Ellen": {"years": "1994-1998", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    # 2010s-2020s
    "Modern Family": {"years": "2009-2020", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "Black-ish": {"years": "2014-2022", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday", "wednesday"]},
    "Scandal": {"years": "2012-2018", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "How to Get Away with Murder": {"years": "2014-2020", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "Grey's Anatomy": {"years": "2005-present", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "Lost": {"years": "2004-2010", "network": "ABC", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["wednesday"]},
    "Desperate Housewives": {"years": "2004-2012", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "The Goldbergs": {"years": "2013-2023", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "The Middle": {"years": "2009-2018", "network": "ABC", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "Once Upon a Time": {"years": "2011-2018", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Castle": {"years": "2009-2016", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "The Bachelor": {"years": "2002-present", "network": "ABC", "genre": "Reality", "runtime": 120, "day_slots": ["monday"]},
    "Boston Legal": {"years": "2004-2008", "network": "ABC", "genre": "Drama", "runtime": 60, "day_slots": ["sunday", "tuesday"]},
    "America's Funniest Home Videos": {"years": "1989-present", "network": "ABC", "genre": "Comedy", "runtime": 60, "day_slots": ["sunday"]},
    # --- FOX ---
    "The Simpsons": {"years": "1989-present", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday", "thursday"]},
    "Married... with Children": {"years": "1987-1997", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "The X-Files": {"years": "1993-2002", "network": "FOX", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday", "sunday"]},
    "Beverly Hills, 90210": {"years": "1990-2000", "network": "FOX", "genre": "Drama", "runtime": 60, "day_slots": ["thursday", "wednesday"]},
    "Melrose Place": {"years": "1992-1999", "network": "FOX", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "In Living Color": {"years": "1990-1994", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "Martin": {"years": "1992-1997", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday", "thursday"]},
    "Living Single": {"years": "1993-1998", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday", "thursday"]},
    "Party of Five": {"years": "1994-2000", "network": "FOX", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    "King of the Hill": {"years": "1997-2010", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "Futurama": {"years": "1999-2003", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "That '70s Show": {"years": "1998-2006", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday", "wednesday"]},
    "Malcolm in the Middle": {"years": "2000-2006", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "21 Jump Street": {"years": "1987-1991", "network": "FOX", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "America's Most Wanted": {"years": "1988-2012", "network": "FOX", "genre": "Reality", "runtime": 60, "day_slots": ["saturday", "sunday"]},
    "Cops": {"years": "1989-2013", "network": "FOX", "genre": "Reality", "runtime": 30, "day_slots": ["saturday"]},
    "Family Guy": {"years": "1999-present", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "24": {"years": "2001-2010", "network": "FOX", "genre": "Action", "runtime": 60, "day_slots": ["tuesday", "monday"]},
    "Ally McBeal": {"years": "1997-2002", "network": "FOX", "genre": "Comedy", "runtime": 60, "day_slots": ["monday"]},
    # 2010s-2020s
    "Glee": {"years": "2009-2015", "network": "FOX", "genre": "Comedy", "runtime": 60, "day_slots": ["tuesday", "thursday"]},
    "New Girl": {"years": "2011-2018", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "Brooklyn Nine-Nine (FOX)": {"years": "2013-2018", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday", "sunday"]},
    "Bones": {"years": "2005-2017", "network": "FOX", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday", "thursday"]},
    "House": {"years": "2004-2012", "network": "FOX", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday", "monday"]},
    "Empire": {"years": "2015-2020", "network": "FOX", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    "Gotham": {"years": "2014-2019", "network": "FOX", "genre": "Action", "runtime": 60, "day_slots": ["monday", "thursday"]},
    "Bob's Burgers": {"years": "2011-present", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "The Masked Singer": {"years": "2019-present", "network": "FOX", "genre": "Reality", "runtime": 60, "day_slots": ["wednesday"]},
    "9-1-1": {"years": "2018-present", "network": "FOX", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "The Orville": {"years": "2017-2019", "network": "FOX", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["thursday", "sunday"]},
    "Arrested Development": {"years": "2003-2006", "network": "FOX", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday", "monday"]},
    "Millennium": {"years": "1996-1999", "network": "FOX", "genre": "Drama", "runtime": 60, "day_slots": ["friday"]},
    "American Idol": {"years": "2002-2016", "network": "FOX", "genre": "Reality", "runtime": 60, "day_slots": ["tuesday", "wednesday"]},
    # --- PBS ---
    "Masterpiece Theatre": {"years": "1971-present", "network": "PBS", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Nova": {"years": "1974-present", "network": "PBS", "genre": "Documentary", "runtime": 60, "day_slots": ["tuesday", "wednesday"]},
    "Frontline": {"years": "1983-present", "network": "PBS", "genre": "Documentary", "runtime": 60, "day_slots": ["tuesday"]},
    "The NewsHour with Jim Lehrer": {"years": "1975-present", "network": "PBS", "genre": "News", "runtime": 60, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    "Sesame Street": {"years": "1969-present", "network": "PBS", "genre": "Children", "runtime": 60, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    "Mister Rogers' Neighborhood": {"years": "1968-2001", "network": "PBS", "genre": "Children", "runtime": 30, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    "Reading Rainbow": {"years": "1983-2006", "network": "PBS", "genre": "Children", "runtime": 30, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    "Nature": {"years": "1982-present", "network": "PBS", "genre": "Documentary", "runtime": 60, "day_slots": ["sunday"]},
    "American Experience": {"years": "1988-present", "network": "PBS", "genre": "Documentary", "runtime": 60, "day_slots": ["monday", "tuesday"]},
    "Mystery!": {"years": "1980-2008", "network": "PBS", "genre": "Mystery", "runtime": 60, "day_slots": ["thursday"]},
    "This Old House": {"years": "1979-present", "network": "PBS", "genre": "Home", "runtime": 30, "day_slots": ["saturday"]},
    "The Frugal Gourmet": {"years": "1983-1997", "network": "PBS", "genre": "Cooking", "runtime": 30, "day_slots": ["saturday"]},
    "Julia Child & Company": {"years": "1978-2000", "network": "PBS", "genre": "Cooking", "runtime": 30, "day_slots": ["saturday"]},
    "Austin City Limits": {"years": "1976-present", "network": "PBS", "genre": "Music", "runtime": 60, "day_slots": ["saturday"]},
    "Great Performances": {"years": "1972-present", "network": "PBS", "genre": "Arts", "runtime": 60, "day_slots": ["friday"]},
    "Antiques Roadshow": {"years": "1997-present", "network": "PBS", "genre": "Reality", "runtime": 60, "day_slots": ["monday"]},
    "Ken Burns Documentaries": {"years": "1981-present", "network": "PBS", "genre": "Documentary", "runtime": 60, "day_slots": ["sunday", "monday"]},
    "Cosmos": {"years": "1980-1980", "network": "PBS", "genre": "Documentary", "runtime": 60, "day_slots": ["sunday"]},
    "The Victory Garden": {"years": "1975-2005", "network": "PBS", "genre": "Home", "runtime": 30, "day_slots": ["saturday"]},
    "Washington Week": {"years": "1967-present", "network": "PBS", "genre": "News", "runtime": 30, "day_slots": ["friday"]},
    # --- WB (The WB) ---
    "7th Heaven": {"years": "1996-2007", "network": "WB", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "Buffy the Vampire Slayer": {"years": "1997-2001", "network": "WB", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "Dawson's Creek": {"years": "1998-2003", "network": "WB", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday", "tuesday"]},
    "Charmed": {"years": "1998-2006", "network": "WB", "genre": "Drama", "runtime": 60, "day_slots": ["thursday", "sunday"]},
    "Felicity": {"years": "1998-2002", "network": "WB", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday", "sunday"]},
    "Smallville (WB)": {"years": "2001-2006", "network": "WB", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["tuesday"]},
    "Gilmore Girls (WB)": {"years": "2000-2007", "network": "WB", "genre": "Comedy", "runtime": 60, "day_slots": ["tuesday", "thursday"]},
    "One Tree Hill (WB)": {"years": "2003-2006", "network": "WB", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "Everwood": {"years": "2002-2006", "network": "WB", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "Reba": {"years": "2001-2006", "network": "WB", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "The Jamie Foxx Show": {"years": "1996-2001", "network": "WB", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "The Steve Harvey Show": {"years": "1996-2002", "network": "WB", "genre": "Comedy", "runtime": 30, "day_slots": ["friday"]},
    "The Wayans Bros.": {"years": "1995-1999", "network": "WB", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "Unhappily Ever After": {"years": "1995-1999", "network": "WB", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "Smart Guy": {"years": "1997-1999", "network": "WB", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "Angel": {"years": "1999-2004", "network": "WB", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday", "wednesday"]},
    "Supernatural (WB)": {"years": "2005-2006", "network": "WB", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "Roswell": {"years": "1999-2002", "network": "WB", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["wednesday"]},
    "Popular": {"years": "1999-2001", "network": "WB", "genre": "Comedy", "runtime": 60, "day_slots": ["friday"]},
    # --- UPN ---
    "Star Trek: Voyager": {"years": "1995-2001", "network": "UPN", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["monday", "wednesday"]},
    "Star Trek: Enterprise": {"years": "2001-2005", "network": "UPN", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["wednesday"]},
    "Moesha": {"years": "1996-2001", "network": "UPN", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "The Parkers": {"years": "1999-2004", "network": "UPN", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Girlfriends": {"years": "2000-2006", "network": "UPN", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Half & Half": {"years": "2002-2006", "network": "UPN", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "One on One": {"years": "2001-2006", "network": "UPN", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Everybody Hates Chris": {"years": "2005-2006", "network": "UPN", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Veronica Mars (UPN)": {"years": "2004-2006", "network": "UPN", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday", "wednesday"]},
    "America's Next Top Model (UPN)": {"years": "2003-2006", "network": "UPN", "genre": "Reality", "runtime": 60, "day_slots": ["wednesday"]},
    "WWE SmackDown": {"years": "1999-2006", "network": "UPN", "genre": "Sports", "runtime": 120, "day_slots": ["thursday"]},
    "The Hughleys": {"years": "1998-2002", "network": "UPN", "genre": "Comedy", "runtime": 30, "day_slots": ["monday", "friday"]},
    "Malcolm & Eddie": {"years": "1996-2000", "network": "UPN", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Platypus Man": {"years": "1995-1995", "network": "UPN", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "The Sentinel": {"years": "1996-1999", "network": "UPN", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["wednesday"]},
    "7 Days": {"years": "1998-2001", "network": "UPN", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["wednesday"]},
    # --- CW ---
    "Supernatural (CW)": {"years": "2006-2020", "network": "CW", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "Smallville (CW)": {"years": "2006-2011", "network": "CW", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["thursday"]},
    "One Tree Hill (CW)": {"years": "2006-2012", "network": "CW", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "Gossip Girl": {"years": "2007-2012", "network": "CW", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "The Vampire Diaries": {"years": "2009-2017", "network": "CW", "genre": "Drama", "runtime": 60, "day_slots": ["thursday"]},
    "90210": {"years": "2008-2013", "network": "CW", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "America's Next Top Model (CW)": {"years": "2006-2015", "network": "CW", "genre": "Reality", "runtime": 60, "day_slots": ["wednesday"]},
    "Gilmore Girls (CW)": {"years": "2006-2007", "network": "CW", "genre": "Comedy", "runtime": 60, "day_slots": ["tuesday"]},
    "Veronica Mars (CW)": {"years": "2006-2007", "network": "CW", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "Arrow": {"years": "2012-2020", "network": "CW", "genre": "Action", "runtime": 60, "day_slots": ["wednesday"]},
    "The Flash": {"years": "2014-present", "network": "CW", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["tuesday"]},
    "Jane the Virgin": {"years": "2014-2019", "network": "CW", "genre": "Comedy", "runtime": 60, "day_slots": ["monday"]},
    "Crazy Ex-Girlfriend": {"years": "2015-2019", "network": "CW", "genre": "Comedy", "runtime": 60, "day_slots": ["friday"]},
    "Riverdale": {"years": "2017-present", "network": "CW", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    "Supergirl": {"years": "2016-2021", "network": "CW", "genre": "Action", "runtime": 60, "day_slots": ["monday", "sunday"]},
    "Legends of Tomorrow": {"years": "2016-2022", "network": "CW", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["tuesday", "wednesday"]},
    "The 100": {"years": "2014-2020", "network": "CW", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["wednesday"]},
    "iZombie": {"years": "2015-2019", "network": "CW", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "Batwoman": {"years": "2019-2022", "network": "CW", "genre": "Action", "runtime": 60, "day_slots": ["sunday"]},
    "All American": {"years": "2018-present", "network": "CW", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "Dynasty (CW)": {"years": "2017-2022", "network": "CW", "genre": "Drama", "runtime": 60, "day_slots": ["friday"]},
    "Charmed (CW)": {"years": "2018-2022", "network": "CW", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    # --- Syndication ---
    "Star Trek: The Next Generation": {"years": "1987-1994", "network": "SYNDICATION", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["saturday", "sunday"]},
    "Star Trek: Deep Space Nine": {"years": "1993-1999", "network": "SYNDICATION", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["saturday", "sunday"]},
    "Baywatch": {"years": "1989-2001", "network": "SYNDICATION", "genre": "Drama", "runtime": 60, "day_slots": ["saturday"]},
    "Xena: Warrior Princess": {"years": "1995-2001", "network": "SYNDICATION", "genre": "Action", "runtime": 60, "day_slots": ["saturday", "sunday"]},
    "Hercules: The Legendary Journeys": {"years": "1995-1999", "network": "SYNDICATION", "genre": "Action", "runtime": 60, "day_slots": ["saturday", "sunday"]},
    "Andromeda": {"years": "2000-2005", "network": "SYNDICATION", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["saturday"]},
    "Mutant X": {"years": "2001-2004", "network": "SYNDICATION", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["saturday"]},
    "Earth: Final Conflict": {"years": "1997-2002", "network": "SYNDICATION", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["saturday"]},
    "Stargate SG-1 (Syndication)": {"years": "1997-2002", "network": "SYNDICATION", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday"]},
    "The Outer Limits (Syndication)": {"years": "1995-2002", "network": "SYNDICATION", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday"]},
    "Highlander: The Series": {"years": "1992-1998", "network": "SYNDICATION", "genre": "Action", "runtime": 60, "day_slots": ["saturday"]},
    "Kung Fu: The Legend Continues": {"years": "1993-1997", "network": "SYNDICATION", "genre": "Action", "runtime": 60, "day_slots": ["saturday"]},
    "Soul Train": {"years": "1971-2006", "network": "SYNDICATION", "genre": "Music", "runtime": 60, "day_slots": ["saturday"]},
    "Wheel of Fortune": {"years": "1983-present", "network": "SYNDICATION", "genre": "Game Show", "runtime": 30, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    "Jeopardy!": {"years": "1984-present", "network": "SYNDICATION", "genre": "Game Show", "runtime": 30, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    "Entertainment Tonight": {"years": "1981-present", "network": "SYNDICATION", "genre": "News", "runtime": 30, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    "Judge Judy": {"years": "1996-2021", "network": "SYNDICATION", "genre": "Reality", "runtime": 30, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    "The Oprah Winfrey Show": {"years": "1986-2011", "network": "SYNDICATION", "genre": "Talk", "runtime": 60, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    "Seinfeld (Syndication)": {"years": "1995-present", "network": "SYNDICATION", "genre": "Comedy", "runtime": 30, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    "Friends (Syndication)": {"years": "1998-present", "network": "SYNDICATION", "genre": "Comedy", "runtime": 30, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    # --- HBO ---
    "The Sopranos": {"years": "1999-2007", "network": "HBO", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "The Wire": {"years": "2002-2008", "network": "HBO", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Sex and the City": {"years": "1998-2004", "network": "HBO", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "Game of Thrones": {"years": "2011-2019", "network": "HBO", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Curb Your Enthusiasm": {"years": "2000-2024", "network": "HBO", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "Oz": {"years": "1997-2003", "network": "HBO", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Six Feet Under": {"years": "2001-2005", "network": "HBO", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Deadwood": {"years": "2004-2006", "network": "HBO", "genre": "Western", "runtime": 60, "day_slots": ["sunday"]},
    "True Blood": {"years": "2008-2014", "network": "HBO", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Boardwalk Empire": {"years": "2010-2014", "network": "HBO", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Veep": {"years": "2012-2019", "network": "HBO", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "Westworld": {"years": "2016-2022", "network": "HBO", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["sunday"]},
    "Succession": {"years": "2018-2023", "network": "HBO", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Band of Brothers": {"years": "2001-2001", "network": "HBO", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Big Little Lies": {"years": "2017-2019", "network": "HBO", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Barry": {"years": "2018-2023", "network": "HBO", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "The Last of Us": {"years": "2023-present", "network": "HBO", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Entourage": {"years": "2004-2011", "network": "HBO", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    # --- FX ---
    "The Shield": {"years": "2002-2008", "network": "FX", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "Nip/Tuck": {"years": "2003-2010", "network": "FX", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "It's Always Sunny in Philadelphia": {"years": "2005-present", "network": "FX", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Sons of Anarchy": {"years": "2008-2014", "network": "FX", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday", "wednesday"]},
    "Justified": {"years": "2010-2015", "network": "FX", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "American Horror Story": {"years": "2011-present", "network": "FX", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    "Fargo": {"years": "2014-present", "network": "FX", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "The Americans": {"years": "2013-2018", "network": "FX", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    "Atlanta": {"years": "2016-2022", "network": "FX", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "Archer": {"years": "2009-present", "network": "FX", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Snowfall": {"years": "2017-2023", "network": "FX", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    "The Bear": {"years": "2022-present", "network": "FX", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    "Rescue Me": {"years": "2004-2011", "network": "FX", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday", "wednesday"]},
    # --- AMC ---
    "Mad Men": {"years": "2007-2015", "network": "AMC", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Breaking Bad": {"years": "2008-2013", "network": "AMC", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "The Walking Dead": {"years": "2010-2022", "network": "AMC", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Better Call Saul": {"years": "2015-2022", "network": "AMC", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "Fear the Walking Dead": {"years": "2015-2023", "network": "AMC", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Preacher": {"years": "2016-2019", "network": "AMC", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    "Halt and Catch Fire": {"years": "2014-2017", "network": "AMC", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "Turn: Washington's Spies": {"years": "2014-2017", "network": "AMC", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "The Terror": {"years": "2018-2019", "network": "AMC", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "Killing Eve": {"years": "2018-2022", "network": "AMC", "genre": "Drama", "runtime": 60, "day_slots": ["sunday"]},
    # --- USA Network ---
    "Monk": {"years": "2002-2009", "network": "USA", "genre": "Mystery", "runtime": 60, "day_slots": ["friday"]},
    "Psych": {"years": "2006-2014", "network": "USA", "genre": "Comedy", "runtime": 60, "day_slots": ["friday"]},
    "Burn Notice": {"years": "2007-2013", "network": "USA", "genre": "Action", "runtime": 60, "day_slots": ["thursday"]},
    "Royal Pains": {"years": "2009-2016", "network": "USA", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "White Collar": {"years": "2009-2014", "network": "USA", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday"]},
    "Suits": {"years": "2011-2019", "network": "USA", "genre": "Drama", "runtime": 60, "day_slots": ["tuesday", "wednesday"]},
    "Mr. Robot": {"years": "2015-2019", "network": "USA", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    "Covert Affairs": {"years": "2010-2014", "network": "USA", "genre": "Action", "runtime": 60, "day_slots": ["tuesday"]},
    "WWE Raw": {"years": "1993-present", "network": "USA", "genre": "Sports", "runtime": 120, "day_slots": ["monday"]},
    "La Femme Nikita": {"years": "1997-2001", "network": "USA", "genre": "Action", "runtime": 60, "day_slots": ["sunday"]},
    "The Dead Zone": {"years": "2002-2007", "network": "USA", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["sunday"]},
    "Necessary Roughness": {"years": "2011-2013", "network": "USA", "genre": "Drama", "runtime": 60, "day_slots": ["wednesday"]},
    # --- Sci-Fi Channel / Syfy ---
    "Battlestar Galactica": {"years": "2004-2009", "network": "SYFY", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday"]},
    "Stargate SG-1": {"years": "2002-2007", "network": "SYFY", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday"]},
    "Stargate Atlantis": {"years": "2004-2009", "network": "SYFY", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday"]},
    "Farscape": {"years": "1999-2003", "network": "SYFY", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday"]},
    "The Expanse (Syfy)": {"years": "2015-2018", "network": "SYFY", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["wednesday"]},
    "Warehouse 13": {"years": "2009-2014", "network": "SYFY", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["tuesday"]},
    "Eureka": {"years": "2006-2012", "network": "SYFY", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday", "tuesday"]},
    "12 Monkeys": {"years": "2015-2018", "network": "SYFY", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday"]},
    "Killjoys": {"years": "2015-2019", "network": "SYFY", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday"]},
    "Dark Matter": {"years": "2015-2017", "network": "SYFY", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday"]},
    "Lexx": {"years": "2000-2002", "network": "SYFY", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday"]},
    "Sliders": {"years": "1998-2000", "network": "SYFY", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["friday"]},
    "The Magicians": {"years": "2015-2020", "network": "SYFY", "genre": "Sci-Fi", "runtime": 60, "day_slots": ["wednesday"]},
    # --- Comedy Central ---
    "South Park": {"years": "1997-present", "network": "COMEDY CENTRAL", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "The Daily Show": {"years": "1996-present", "network": "COMEDY CENTRAL", "genre": "Talk", "runtime": 30, "day_slots": ["monday", "tuesday", "wednesday", "thursday"]},
    "The Colbert Report": {"years": "2005-2014", "network": "COMEDY CENTRAL", "genre": "Talk", "runtime": 30, "day_slots": ["monday", "tuesday", "wednesday", "thursday"]},
    "Chappelle's Show": {"years": "2003-2006", "network": "COMEDY CENTRAL", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "Reno 911!": {"years": "2003-2009", "network": "COMEDY CENTRAL", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "Broad City": {"years": "2014-2019", "network": "COMEDY CENTRAL", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "Key & Peele": {"years": "2012-2015", "network": "COMEDY CENTRAL", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "Workaholics": {"years": "2011-2017", "network": "COMEDY CENTRAL", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "Tosh.0": {"years": "2009-2020", "network": "COMEDY CENTRAL", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "Drunk History": {"years": "2013-2019", "network": "COMEDY CENTRAL", "genre": "Comedy", "runtime": 30, "day_slots": ["tuesday"]},
    "Crank Yankers": {"years": "2002-2020", "network": "COMEDY CENTRAL", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    "The Man Show": {"years": "1999-2004", "network": "COMEDY CENTRAL", "genre": "Comedy", "runtime": 30, "day_slots": ["wednesday"]},
    # --- Nickelodeon ---
    "Rugrats": {"years": "1991-2004", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["saturday", "sunday"]},
    "SpongeBob SquarePants": {"years": "1999-present", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["saturday"]},
    "All That": {"years": "1994-2005", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["saturday"]},
    "Kenan & Kel": {"years": "1996-2000", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["saturday"]},
    "Doug": {"years": "1991-1994", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["sunday"]},
    "Clarissa Explains It All": {"years": "1991-1994", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["saturday"]},
    "The Adventures of Pete & Pete": {"years": "1993-1996", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["sunday"]},
    "Are You Afraid of the Dark?": {"years": "1992-2000", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["saturday"]},
    "Hey Arnold!": {"years": "1996-2004", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["saturday"]},
    "The Fairly OddParents": {"years": "2001-2017", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["saturday"]},
    "Drake & Josh": {"years": "2004-2007", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["sunday"]},
    "iCarly": {"years": "2007-2012", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["saturday"]},
    "Ren & Stimpy": {"years": "1991-1996", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["sunday"]},
    "Rocko's Modern Life": {"years": "1993-1996", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["sunday"]},
    "The Wild Thornberrys": {"years": "1998-2004", "network": "NICKELODEON", "genre": "Children", "runtime": 30, "day_slots": ["saturday"]},
    # --- Cartoon Network ---
    "Dexter's Laboratory": {"years": "1996-2003", "network": "CARTOON NETWORK", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    "The Powerpuff Girls": {"years": "1998-2005", "network": "CARTOON NETWORK", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    "Johnny Bravo": {"years": "1997-2004", "network": "CARTOON NETWORK", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    "Ed, Edd n Eddy": {"years": "1999-2009", "network": "CARTOON NETWORK", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    "Courage the Cowardly Dog": {"years": "1999-2002", "network": "CARTOON NETWORK", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    "Samurai Jack": {"years": "2001-2017", "network": "CARTOON NETWORK", "genre": "Children", "runtime": 30, "day_slots": ["saturday"]},
    "Ben 10": {"years": "2005-2008", "network": "CARTOON NETWORK", "genre": "Children", "runtime": 30, "day_slots": ["saturday"]},
    "Adventure Time": {"years": "2010-2018", "network": "CARTOON NETWORK", "genre": "Children", "runtime": 30, "day_slots": ["monday"]},
    "Regular Show": {"years": "2010-2017", "network": "CARTOON NETWORK", "genre": "Children", "runtime": 30, "day_slots": ["monday"]},
    "Steven Universe": {"years": "2013-2019", "network": "CARTOON NETWORK", "genre": "Children", "runtime": 30, "day_slots": ["thursday"]},
    "The Amazing World of Gumball": {"years": "2011-2019", "network": "CARTOON NETWORK", "genre": "Children", "runtime": 30, "day_slots": ["thursday"]},
    # Adult Swim block
    "Robot Chicken": {"years": "2005-present", "network": "ADULT SWIM", "genre": "Comedy", "runtime": 15, "day_slots": ["sunday"]},
    "Aqua Teen Hunger Force": {"years": "2000-2015", "network": "ADULT SWIM", "genre": "Comedy", "runtime": 15, "day_slots": ["sunday"]},
    "The Venture Bros.": {"years": "2003-2018", "network": "ADULT SWIM", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "Rick and Morty": {"years": "2013-present", "network": "ADULT SWIM", "genre": "Comedy", "runtime": 30, "day_slots": ["sunday"]},
    "Harvey Birdman, Attorney at Law": {"years": "2001-2007", "network": "ADULT SWIM", "genre": "Comedy", "runtime": 15, "day_slots": ["sunday"]},
    "Metalocalypse": {"years": "2006-2013", "network": "ADULT SWIM", "genre": "Comedy", "runtime": 15, "day_slots": ["sunday"]},
    "Tim and Eric Awesome Show, Great Job!": {"years": "2007-2010", "network": "ADULT SWIM", "genre": "Comedy", "runtime": 15, "day_slots": ["sunday"]},
    # --- Disney Channel ---
    "Lizzie McGuire": {"years": "2001-2004", "network": "DISNEY CHANNEL", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    "That's So Raven": {"years": "2003-2007", "network": "DISNEY CHANNEL", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    "Hannah Montana": {"years": "2006-2011", "network": "DISNEY CHANNEL", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    "Kim Possible": {"years": "2002-2007", "network": "DISNEY CHANNEL", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    "Wizards of Waverly Place": {"years": "2007-2012", "network": "DISNEY CHANNEL", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    "The Suite Life of Zack & Cody": {"years": "2005-2008", "network": "DISNEY CHANNEL", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    "Good Luck Charlie": {"years": "2010-2014", "network": "DISNEY CHANNEL", "genre": "Children", "runtime": 30, "day_slots": ["sunday"]},
    "Gravity Falls": {"years": "2012-2016", "network": "DISNEY CHANNEL", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    "Phineas and Ferb": {"years": "2007-2015", "network": "DISNEY CHANNEL", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    "Boy Meets World (Disney)": {"years": "2000-2003", "network": "DISNEY CHANNEL", "genre": "Children", "runtime": 30, "day_slots": ["saturday"]},
    "The Proud Family": {"years": "2001-2005", "network": "DISNEY CHANNEL", "genre": "Children", "runtime": 30, "day_slots": ["friday"]},
    # --- MTV ---
    "The Real World": {"years": "1992-2017", "network": "MTV", "genre": "Reality", "runtime": 30, "day_slots": ["tuesday", "wednesday"]},
    "Beavis and Butt-Head": {"years": "1993-2011", "network": "MTV", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Daria": {"years": "1997-2002", "network": "MTV", "genre": "Comedy", "runtime": 30, "day_slots": ["monday"]},
    "Jackass": {"years": "2000-2002", "network": "MTV", "genre": "Reality", "runtime": 30, "day_slots": ["sunday"]},
    "MTV Unplugged": {"years": "1989-present", "network": "MTV", "genre": "Music", "runtime": 60, "day_slots": ["thursday"]},
    "Total Request Live": {"years": "1998-2008", "network": "MTV", "genre": "Music", "runtime": 60, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    "Pimp My Ride": {"years": "2004-2007", "network": "MTV", "genre": "Reality", "runtime": 30, "day_slots": ["sunday"]},
    "Punk'd": {"years": "2003-2015", "network": "MTV", "genre": "Reality", "runtime": 30, "day_slots": ["sunday"]},
    "Cribs": {"years": "2000-2021", "network": "MTV", "genre": "Reality", "runtime": 30, "day_slots": ["sunday"]},
    "Jersey Shore": {"years": "2009-2012", "network": "MTV", "genre": "Reality", "runtime": 60, "day_slots": ["thursday"]},
    "Teen Wolf": {"years": "2011-2017", "network": "MTV", "genre": "Drama", "runtime": 60, "day_slots": ["monday"]},
    "Ridiculousness": {"years": "2011-present", "network": "MTV", "genre": "Comedy", "runtime": 30, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    "Celebrity Deathmatch": {"years": "1998-2007", "network": "MTV", "genre": "Comedy", "runtime": 30, "day_slots": ["thursday"]},
    # --- DuMont ---
    "Captain Video and His Video Rangers": {"years": "1949-1955", "network": "DUMONT", "genre": "Sci-Fi", "runtime": 30, "day_slots": ["monday", "tuesday", "wednesday", "thursday", "friday"]},
    "The Honeymooners (DuMont)": {"years": "1951-1955", "network": "DUMONT", "genre": "Comedy", "runtime": 30, "day_slots": ["saturday"]},
    "Cavalcade of Stars": {"years": "1949-1952", "network": "DUMONT", "genre": "Variety", "runtime": 60, "day_slots": ["friday"]},
    "Life Is Worth Living": {"years": "1952-1955", "network": "DUMONT", "genre": "Talk", "runtime": 30, "day_slots": ["tuesday"]},
    "Rocky King, Detective": {"years": "1950-1954", "network": "DUMONT", "genre": "Drama", "runtime": 30, "day_slots": ["sunday"]},
    "Down You Go": {"years": "1951-1956", "network": "DUMONT", "genre": "Game Show", "runtime": 30, "day_slots": ["friday"]},
}
